#!/bin/sh

# session
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway

# misc wayland stuff
export MOZ_ENABLE_WAYLAND=1
export GDK_BACKEND=wayland
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

# theme
export GTK_THEME=Adwaita:dark
#export GTK2_RC_FILES=/usr/share/themes/Adwaita-dark/gtk-2.0/gtkrc

# we have the if-else just in case sway changes its install location in later installs.
if [ -f "/usr/local/bin/sway" ]; then
/usr/loal/bin/sway $@
else
/usr/bin/sway $@
fi
